#!/bin/bash -e
dir=$1; branch=$2
if [[ -z $dir || -z $branch ]]; then echo "Usage: $0 <dir> <branch>"; exit 1; fi
cd "$dir"
if [[ -n $(git status --porcelain --untracked-files=no) ]]; then
  new_branch="discarded-$(hostname -s)-$(date +%s.%N)"
  echo "Local changes exist; saving into new branch $new_branch and discarding"
  git -c "user.name=$0" -c "user.email=$(id -un)@$(hostname)" commit --quiet --all --message='Changes discarded during triggered pull'
  git branch "$new_branch"
fi
git checkout --quiet "$branch"
git fetch --quiet --all
git reset --quiet --hard origin/"$branch"
